// Training paragraph constants -- 15 diverse texts for voice profile calibration
export const TRAINING_PARAGRAPHS: readonly string[] = [
  "The weather has been quite pleasant this week, though yesterday's forecast was slightly off. I brought my umbrella anyway, just in case; it's better to be prepared than caught in the rain. Their house is about fifteen minutes from here, right past the old library. We're planning to meet there at noon — or maybe twelve-thirty, if the traffic is heavy. \"Would you rather walk or drive?\" she asked. I'd prefer to walk, but it depends on whether the clouds clear up.",

  "The API endpoint returns a JSON payload containing the user's repository metadata and commit history. I refactored the authentication middleware to use asynchronous callbacks instead of synchronous blocking calls. Our CI/CD pipeline runs ESLint, then executes the TypeScript compiler with strict null checks enabled. The PostgreSQL query was hitting a deadlock because two concurrent transactions held conflicting row-level locks. \"Have you pushed your branch to the remote?\" she asked during the code review. I rebased onto main, resolved the merge conflict in the config file, and force-pushed the fix.",

  "Dr. Ramirez ordered a comprehensive metabolic panel along with a thyroid-stimulating hormone assay for the patient. The echocardiogram revealed mild mitral valve regurgitation, though no immediate surgical intervention was recommended. Her hemoglobin A1C levels have improved significantly since starting metformin; the endocrinologist was pleased with the progress. We should schedule a follow-up colonoscopy and review the histopathology results from the previous biopsy. The differential diagnosis includes both gastroesophageal reflux disease and eosinophilic esophagitis — further testing is warranted.",

  "Priya Chakraborty and Xiaowei Zhang co-authored the research paper with contributions from Oluwaseun Adeyemi and Bjorn Thorvaldsen. The conference in Reykjavik was organized by Siobhan O'Callaghan, who also invited Nguyen Thi Minh from Ho Chi Minh City. \"Has Dmitri Volkov confirmed his attendance?\" asked Alessandra Petrova during the planning call. Kofi Mensah-Asante flew in from Accra, while Takeshi Kobayashi arrived from Osaka the previous evening. The keynote address was delivered by Fatima al-Rashidi, whose work on computational linguistics has influenced researchers from Sao Paulo to Bangalore.",

  "The quarterly report for Q3 2025 showed revenue of $4.7 million, up 12.3% from the previous quarter. On March 15th, 1993, the team processed exactly 8,412 transactions in a single twenty-four-hour period. The building at 1600 Pennsylvania Avenue was constructed between 1792 and 1800. Our flight departs at 7:45 AM on December 31st, arriving at 2:15 PM local time. The ratio of defective parts was 3 out of every 10,000 — roughly 0.03%. She celebrated her forty-second birthday on the 8th of November, 2024.",

  "The CEO announced that our SaaS platform will comply with both GDPR and HIPAA regulations by Q2. NASA's latest report on the ISS references UV radiation levels that exceed OSHA's recommended exposure limits. \"Did the PM send the updated ETA to the QA team?\" asked the VP of engineering during the standup. Our DNS records point to an AWS load balancer, but the SSL certificate expired — IT is renewing it ASAP. The FAQ section covers topics like SMTP configuration, OAuth 2.0 setup, and REST API rate limiting.",

  "Stop. I mean it — put that down right now before you break something. The fundamental problem with our approach to urban planning in the twenty-first century is that we continue to prioritize automobile infrastructure over pedestrian-friendly spaces, mixed-use zoning, and accessible public transit networks that serve communities equitably. Rain fell. She grabbed her coat, stuffed the notebook into her bag, glanced at the clock on the wall, muttered something under her breath, and rushed out the door. Why? Because the bus only comes once an hour.",

  "What on earth happened to the deployment pipeline overnight?! I checked the logs at 6 AM and everything was green. Did someone merge directly to production without running the test suite? That's absolutely unacceptable! \"Wasn't there a branch protection rule in place?\" asked the lead engineer, visibly frustrated. How are we supposed to maintain uptime if critical safeguards keep getting bypassed? Wait — are you telling me the staging environment was down too? Incredible. We need to fix this immediately and schedule a post-mortem before end of day.",

  "Dear Ms. Thompson, I hope this message finds you well. Per our conversation on Tuesday, I've attached the revised proposal reflecting the updated scope and timeline. The deliverables for Phase 2 are now scheduled for completion by June 30th; however, this is contingent upon receiving stakeholder approval no later than April 15th. Please let me know if you have any questions or concerns regarding the budget allocation. I look forward to your feedback at your earliest convenience. Best regards, Marcus Chen, Senior Project Manager.",

  "So yeah, I was gonna grab coffee with Jake but he totally bailed on me last minute. He said something about his car making a weird noise — like a clunking sound, I dunno. Anyway, I ended up going to that new place on Fifth Street; have you been there yet? Their oat milk latte is seriously amazing. Oh, and guess what: I ran into Sarah! She's doing great, by the way. We talked for like an hour about her new job — she's working remotely now, which is pretty cool.",

  "The `AudioRecorder` module initializes a 16kHz mono input stream using the system's default audio device. When `start_recording()` is called, a ring buffer captures raw PCM samples with a 500-millisecond pre-roll window. Voice activity detection filters silent frames before passing audio data to the Whisper inference engine. Note: the `--model` flag accepts values of `tiny`, `base`, `small`, or `medium` (default: `tiny`). All audio processing occurs in memory; no temporary files are written to disk. See the architecture diagram in Section 4.2 for the complete data flow.",

  "The lighthouse keeper climbed the spiral staircase for what felt like the thousandth time, her lantern casting jagged shadows against the damp stone walls. Outside, the sea thrashed and howled — a beast that knew no master. She paused at the narrow window, watching the horizon swallow the last sliver of twilight. \"There's a ship out there,\" she whispered to no one. The fog was thick enough to taste: salt, rust, and something older. She lit the great lamp and prayed its beam would cut through the darkness in time.",

  "Although the committee had originally proposed a three-phase rollout strategy that would span approximately eighteen months and require coordination between the engineering, design, and product management departments, the executive team decided — after reviewing the competitive landscape and consulting with external advisors who specialize in go-to-market acceleration — to compress the entire initiative into a single, aggressive nine-month timeline, which meant that every team would need to reprioritize their existing commitments, hire additional contractors, and accept a higher degree of technical debt than anyone was truly comfortable with. The decision was controversial. It stood.",

  "The archaeologist's serendipitous discovery of a cuneiform tablet near the ziggurat fundamentally altered our understanding of Mesopotamian jurisprudence. Her interlocutor, a laconic etymologist, questioned whether the inscription's meaning was truly unequivocal or merely an artifact of pareidolia in the translation process. The ephemeral beauty of bioluminescent plankton — those phosphorescent organisms that illuminate littoral waters — belies the sophisticated biochemistry underpinning their luminescence. \"Sesquipedalian prose,\" he remarked with a sardonic grin, \"is the hallmark of someone who owns a thesaurus but lacks verisimilitude.\" She found his superciliousness insufferable.",

  "On January 3rd, 2026, Dr. Ananya Krishnamurthy submitted PR #847 to the open-source NLP repository maintained by Bjorn Eriksson's team in Stockholm. \"Does the BERT tokenizer handle diacritical marks correctly?\" she asked in the code review — a reasonable question, given that 23.7% of their user base speaks languages with non-ASCII orthography. The CI pipeline ran for 14 minutes; ESLint passed, but the GPU-accelerated inference benchmark regressed by 0.8 milliseconds. \"That's negligible!\" exclaimed the QA lead. Meanwhile, Kofi messaged the Slack channel: \"Hey y'all, I just grabbed tacos — anyone want some? Also, the HIPAA audit report is due by EOD Friday.\"",
] as const;

export const TOTAL_PARAGRAPHS = TRAINING_PARAGRAPHS.length;
